apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: "mongodb"
spec:
  serviceName: "mongodb-internal"
  replicas: 3
  selector:
    matchLabels:
      name: "mongodb"
  template:
    metadata:
      labels:
        name: "mongodb"
    spec:
      containers:
      - name: mongodb-container
        image: registry.access.redhat.com/rhscl/mongodb-34-rhel7:latest
        args: 
          - "run-mongod-replication"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: "mongo-data"
          mountPath: "/var/lib/mongodb/data"
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        env:
          - name: MONGODB_DATABASE
            value: "mongodb"
          - name: MONGODB_USER
            value: "mongodb"
          - name: MONGODB_PASSWORD
            value: "mongodb"
          - name: MONGODB_ADMIN_PASSWORD
            value: "mongodb"
          - name: MONGODB_REPLICA_NAME
            value: "rs0"
          - name: MONGODB_KEYFILE_VALUE
            value: "12345678901234567890"
          - name: MONGODB_SERVICE_NAME
            value: "mongodb-internal"
        readinessProbe:
          exec:
            command:
              - stat 
              - /tmp/initialized
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          initialDelaySeconds: 15
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
