apiVersion: v1
kind: Service
metadata:
  name: "mongodb-internal"
  labels:
    name: "mongodb"
  annotations: 
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
    - name: mongodb
      port: 27017
  selector: 
    name: "mongodb"
