apiVersion: template.openshift.io/v1
kind: Template
metadata:
  creationTimestamp: null
  name: pipelines-bc
objects:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    name: ${APPLICATION_NAME}-pipeline
    labels:
      build: ${APPLICATION_NAME}-pipeline
  spec:
    source:
      git:
        uri: https://github.com/skoussou/ocp_appdev_template.git
      sourceSecret:
        name: github-secret
      contextDir: ${CONTEXT_DIR}
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
        env:
        - name: "GUID"
          value: ${GUID}
        - name: "CLUSTER"
          value: ${CLUSTER_NAME}
parameters:
- description: The CONTEXT_DIR for the project context directorywithin the repository
  displayName: Project Context Dir 
  name: CONTEXT_DIR
  required: true
- description: The Name to tag all objects of this Pipeline bc
  displayName: The Application Name 
  name: APPLICATION_NAME
  required: true
- description: The GUID prefix of the parks-dev project 
  displayName: GUID 
  name: GUID
  required: true
- description: The Name of the cluster the project is running in
  displayName: The Cluster Name 
  name: CLUSTER_NAME
  required: true
