apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: parks-prod-apps-dc-frontend
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APPLICATION_NAME}
    name: ${APPLICATION_NAME}-${COLOR}
  spec:
    replicas: 1
    selector:
      app: ${APPLICATION_NAME}
      deploymentconfig: ${APPLICATION_NAME}-${COLOR}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APPLICATION_NAME}
          deploymentconfig: ${APPLICATION_NAME}-${COLOR}
      spec:
        containers:
        - env:
          - name: APPNAME
            valueFrom:
              configMapKeyRef:
                key: APPNAME
                name: ${APPLICATION_NAME}-${COLOR}-config
          image: docker-registry.default.svc:5000/${GUID}-parks-dev/${APPLICATION_NAME}:0.0
          imagePullPolicy: IfNotPresent
          name: ${APPLICATION_NAME}-${COLOR}
          livenessProbe:
            exec:
              command:
              - echo
              - ok
            failureThreshold: 3
            initialDelaySeconds: 60
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /ws/healthz/
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers: []
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  data:
    APPNAME: ${APPNAME_LABEL}
  kind: ConfigMap
  metadata:
    name: ${APPLICATION_NAME}-${COLOR}-config
parameters:
- description: The Name of the backend application to create a suitable deployment for 
  displayName: APPLICATION_NAME
  name: APPLICATION_NAME
  required: true
- description: The Color of the deployment (blue/green) of the backend application to create a deployment for 
  displayName: COLOR
  name: COLOR
  required: true
- description: The Name Label for the application to be reported from the /info endpoint (eg. MLB Parks (Blue))
  displayName: Info Label Name
  name: APPNAME_LABEL
  required: true
- description: The GUID prefix of the parks-dev project 
  displayName: GUID 
  name: GUID
  required: true
